vcpkg install assimp:%VCPKG_ARCH%
vcpkg install boost-disjoint-sets:%VCPKG_ARCH%
vcpkg install boost-dynamic-bitset:%VCPKG_ARCH%
vcpkg install boost-filesystem:%VCPKG_ARCH%
vcpkg install boost-graph:%VCPKG_ARCH%
vcpkg install boost-odeint:%VCPKG_ARCH%
vcpkg install boost-program-options:%VCPKG_ARCH%
vcpkg install boost-serialization:%VCPKG_ARCH%
vcpkg install boost-system:%VCPKG_ARCH%
vcpkg install boost-test:%VCPKG_ARCH%
vcpkg install boost-ublas:%VCPKG_ARCH%
vcpkg install eigen3:%VCPKG_ARCH%
vcpkg install fcl:%VCPKG_ARCH%