# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/hana
    REF boost-1.68.0
    SHA512 93b20dc496ac6fa58ae75d523b8782b7c17398e93286698b48666e59af0c7df7410153dc02a8c4ca940d02ed8b948ea6f47b8f884ae2867e0cc8741e09e643ff
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
